### ISSUE TITLE
Implementar o Modelo Entidade Relacional

### ISSUE THREAD

**Issue by Edgar3g** [Edgar3g/project_db_programa--o#3]
# Implementar Script SQL para Modelo Entidade Relacional Existente

## Descrição

O modelo relacional correspondente ao nosso sistema já foi projetado e está disponível em `/db_er/nome-do-arquivo.png`. Nesta issue, a tarefa é escrever o script SQL que implementará esse Modelo Entidade Relacional no banco de dados.

## Tarefas

- [x] Analisar o modelo relacional existente em `/db_er`.
- [x] Escrever um script SQL que traduza o Modelo Entidade Relacional para a estrutura do banco de dados.
- [x] Incluir comandos para criar tabelas, definir chaves primárias, chaves estrangeiras e outros elementos necessários.
- [x] Testar o script SQL para garantir que o banco de dados seja gerado conforme esperado.

## Contexto

A existência do modelo relacional fornece uma base sólida para a implementação do script SQL. Ao finalizar esta tarefa, teremos um script que pode ser utilizado para gerar o banco de dados de acordo com a estrutura definida no Modelo Entidade Relacional.

## Observações

- Certifique-se de documentar o script SQL com comentários explicativos.
- Ao completar esta tarefa, todos os membros da equipe devem estar cientes das alterações no script de geração do banco de dados.

## Responsavel 

@Alexandre-Gaspar

**Comment by Alexandre-Gaspar** [comment]
O diagrama parece não estar normalizado ainda.
E, acho que para facilitar a consulta de clientes devedores cadastrados no sistema, definir o valor máximo que um cliente pode dever e estipular o prazo do pagamento, tinha de existir uma tabela debt (dívida) que teria os seguintes atributos:

- [ ] tbl_debt

- debt_id (PK)
- start_date & end_date (Para controlar o prazo em que tal dívida deve ser paga)
- id_customer (FK)
- id_product (FK)
- id_employee (FK)
- description (opcional)

E quanto a política de negócio, sugiro que um cliente deve fazer apenas uma dívida.
Faltou também a tabela stock (a partir desta tabela, saberemos qual quantidade de um determinado produto. Logo, a tabela de produtos, receberia uma chave estrangeira, vindo da tabela stock para poder referenciar a quantidade de um determindado produto em estoque.

Notei que a tabela "employee" tem como chave primária "order", tinha de ser "id_employee".

Outras coisas que notar no diagrama, vou dar um sinal.

**Comment by Edgar3g** [comment]
@Alexandre-Gaspar Boa, não implementei as dívidas em uma tabela separada, porque... é possível pegar todos os devedores fazendo uma consulta nas vendas.... 

(Pk errada) sim, acabou por passar enquanto fazia os diagramas... but feel free para corrigir

**Comment by Alexandre-Gaspar** [comment]
@Edgar3g até aí entendi. Agora, quanto a questão de controlar o prazo de pagamento de uma dívida e o valor máximo que se pode fazer em uma dívida, como fica ?

**Comment by Edgar3g** [comment]
> @Edgar3g até aí entendi. Agora, quanto a questão de controlar o prazo de pagamento de uma dívida e o valor máximo que se pode fazer em uma dívida, como fica ?

Regra de negócio!  Vamos colocar como regra de negócio no code

**Comment by Edgar3g** [comment]
> > @Edgar3g até aí entendi. Agora, quanto a questão de controlar o prazo de pagamento de uma dívida e o valor máximo que se pode fazer em uma dívida, como fica ?
> 
> Regra de negócio!  Vamos colocar como regra de negócio no code 

Ou seja, vamos quando o cliente quiser mais dívida, o sistema vai no seu banco e analisa quanto de dívida ele já tem, se atingiu o plafo máximo, o sistema vai soltar um alerta a dizer que ele já tem muita dívida e não poderá fazer mais.

Quanto ao limite para pagamento... Vou analisar novamente a DER para ver esse ponto

**Comment by Alexandre-Gaspar** [comment]
Tá nice. I'm waiting...
